name: bact_cellpose
channels:
  - conda-forge
dependencies:
  - python>3.4,<3.8
  - numba>=0.43.1
  - scipy
  - numpy<=1.16.6
  - matplotlib
  - pandas
  - scikit-image
  - jupyter
  - jupyterlab
  - ipywidgets
  - voila
  - nodejs
  - pip
  - pyqt
  #- openjdk=8
  - dask-jobqueue
  - pip:
    - papermill
    - bokeh>=0.13.0
    - mxnet-mkl==1.5.0
    - opencv-python-headless
    - pyqtgraph==0.11.0rc0
    - natsort
    - google-cloud-storage
    - tqdm
    #- python-bioformats
    - oiffile
    - napari
    - scikit-learn
    - git+https://github.com/guiwitz/bactinfection.git@master#egg=bactinfection
    - git+https://github.com/guiwitz/oirpy.git@master#egg=oirpy
    - cellpose
    - plotnine